spring:
  application:
    name: shawa-cloud
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always # embedded never
  cassandra:
    keyspace-name: shawacloud
    schema-action: recreate # none # create_if_not_exists: гарантирует удаление и воссоздание любых таблиц и пользовательских типов при каждом запуске приложения
    local-datacenter: datacenter1
    contact-points: localhost
#    contact-points: # A contact point is the host where a Cassandra node is running.
#      - casshost-1.tacocloud.com
#      - casshost-2.tacocloud.com
#      - casshost-3.tacocloud.com
    port: 9042
    username: cassandra
    password: 75sdQL57

  datasource:
    generate-unique-name: false
    name: shawacloud
    url: jdbc:cassandra://localhost:9042/shawacloud
#    driver-class-name: com.datastax.oss.driver.api.core.DriverConfigLoader;
#    url: jdbc:h2:file:/h2/shawacloud
#    username: h2
#    password: 75sdQL57
#  jpa:
#    hibernate:
#      ddl-auto: update # none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true
##    database-platform: org.hibernate.dialect.H2Dialect